### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit includes all relevant
documents to the generated HTML doc for HexDocs.pm and leverages on
latest features of ExDoc.

### CODE REVIEW

**Comment by vic** [comment]
Hey @kianmeng, would you be interested in being a maintainer to this repo? I've not used elixir since ~2017, I'll be adding a code-owners file on this repo, so other maintainers (I believe it was three people) can take a look and test/merge PRs sooner than me. If you are willing, you are more than welcome to become a maintainer, just send me your hex.pm username.

**Review by lasseebert — COMMENTED** [review]
This is indeed very nice improvements to the docs :tada: 
I think @vic should review the changes made to the license file.

I wil soon not be using Params professionally anymore (because I change job), so I will probably not be around as a maintainer for this project.

**Comment by kianmeng** [comment]
@vic @lasseebert 

Perhaps put notice in Git repo, Hex info page, [adoptoposs.org](https://adoptoposs.org/) or [elixirforum.com](https://elixirforum.com/) looking for maintainers?

If there are no responses within a month or so, just archived the Git repo (to prevent further PRs), and put "not maintain any more" notice to Git repo and Hex info page.

**Comment by vic** [comment]
are you willing you contribute your time on this ? again, if you do, I'm willing to add you as contributor so you can help fix exactly what you are mentioning about keeping this repo more up to date.

this project has two other maintainers (with merge and hex.pm access for creating releases) but things always depend on these people's availability, something we can never ask for.

Being open source, projects belong to their users, code that once was useful to me and just extracted it into a repo in hope it could be of help to anyone else. you can do whatever you like of it as long as you adhere to the license. 

If you truly care about it, as it seems, the invitation is open to become a maintainer and help those still using this repo, and finally merge this yourself.

**Comment by vic** [comment]
changes lgtm, except for adding a broken link to Twitter.

**Comment by kianmeng** [comment]
@vic Thanks for asking again. Sorry, I'm not looking into adopting any FLOSS projects. :sweat_smile:

**Comment by kianmeng** [comment]
> changes lgtm, except for adding a broken link to Twitter.

@vic FYI. The Twitter link, https://twitter.com/vborja, added README.md in master branch, point to a suspended Twitter account.

Screenshot-20220410222747-1640x1204

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
