### PR TITLE
Compatibility with ecto 2.1.0

### PR DESCRIPTION
**Pull request by lasseebert**
* Relaxed ecto dependency to ~> 2.0
* Removed usage of deprecated Ecto.Changeset.cast/4 in favor of cast/3
in tests and README.

### CODE REVIEW

**Comment by lasseebert** [comment]
Build fails on Elixir 1.2.2 because ecto 2.1.0 now requires Elixir ~> 1.3.

@vic, do you know if we could lock to ecto 2.1.0 for Elixir 1.3.x and ecto 2.0.6 for Elixir 1.2.x in Travis?

**Comment by vic** [comment]
@lasseebert could you change the versions on the .travis file ? most people would be using Elixir 1.3 by now, so I guess it'd be safe to release a new version with your changes and target to 1.3, what do you think?

**Comment by lasseebert** [comment]
@vic, I agree with the targeting of elixir 1.3.

* Updated travis config to use elixir 1.3.4 and 1.4.0-rc.1.
* Updated travis config to use the two latest versions of OTP.
* Fixed elixir 1.4 warnings

**Comment by vic** [comment]
Very nice, thank you !

I'll create a new release now.

**Comment by lasseebert** [comment]
Super :heart:

**Comment by vic** [comment]
@lasseebert just released https://hex.pm/packages/params/2.0.2

**Comment by lasseebert** [comment]
Thanks :)

**Pull request merged**
